language: node_js
dist: trusty
node_js:
- '6.10'
cache:
  directories:
  - node_modules
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy -- --stage prod
  on:
    branch: master
notifications:
  slack:
    secure: IAHR9JQFeGmNcVh7sy0oaTxkqVhJlsuuClK6VnYOCtTnneF+fT3ImIi85x8vTLa5buJr2zcnImBVOOSbCNseogR3FWU8G0jRJ8zrrqMHpn2F+YIOoXSdxzh1sKZjcYw6miQFlyt7nohgIxkA5GQYlksByKDv8ytLKqZNB4oQK6WPryUoMBTW9ataq0Anf393nJLqxMTYn3YtYVnCVPelxpUwOhgM8SHG7Dm7QtvNleCkVi2v0oj14OuQueqcjt80C7cGVp5/XnvuAVlMhOkstZV3XvgOrYrAJlo2SpyIs8yjIlRmvaMKVR5XFjejFnVnVF27eduvGR2fGzJEoTCRNtjeRBUd5ZVlGfXxgWx3NIKwaJgGY5Ti1IoPtNBWt4pQHVU7KN8LvaOlTlpihV8VDlT32NzimVkJ4aFaYB0uY3IXOTrNDxedaCnVl6+jUJO2NCPdiZx/2tID2mOcDAHMXbmvjBxP1gPpzWo3gjLEyqbbL+IpFbu3YwZmXcZiDlwc8XZVDbeLfxR644K2RTd+3Y5rkZFuhuZLabN/w2rZhfJDQEDlLzwa81syOVu+JAw+epAwgHF6Ni1rlFiHyYYqlp2f1pahVlHx7h+Ef+YBT5KB0IF9c5ExiSV4G5Y2o2k2OwKE1QEbaAjJmGKjlJ9yY7Mx5hV0/1VIYy6IPRSI0JU=
before_install:
- npm install -g serverless@^1.19.0
- openssl aes-256-cbc -K $encrypted_27ba3e3449f5_key -iv $encrypted_27ba3e3449f5_iv
  -in .mysportsfeeds.yml.enc -out ./.mysportsfeeds.yml -d
env:
  - AWS_REGION=us-east-1
  global:
  - secure: e6nhNo8Us8kuomc4bEdu8ix8avBuhVMYzGVj/KEsh03lC+wXMXPfprS8hdocIMI6XCRdPt3cHv/BFzfcXnbG+5yXsQ+p/Gnz69MXOmV7CJWKZ18c5vo1uNSRmsPgrZ+/anBO2p3gYuMQXbJsDHjH6K9QsJ94zv8zZeii9zMdATQm/mOTJun+k7nGQw/VZkHksleywRDuhkazcXtdm18bcbWYhm/I9rULO07hUbVPfgOxOqm0Uij563s0bT0zDcrslOd04ZXVpDe0kHdGVLY8Vkb6LC/VpbyUsmMAhnLaBu5/r1lq3GqZPw7o/LE/BZIj/2CMeRYja+mC6xgr1XZVSnTVG7XEgvUE3LyRe1R05uS/an30dPtkxLWfa+Bhcru/ZzYmbkiUVC7ZyZTyD4ODOs3gbuy1UllHF+hQuXc5N8CCOtwnP21WE+pZcQVN+dLasew+Z0pm/4IOk2hhuNlzfLuOxopTwHlOMQMv1GgvnFiWPCTYgytjHU+x2wJHmcI20jL23+teUiiZsGLarx7ifcADCsYXzz4aSgc212G8szHA1cbpFld9LX/MagsxUU+eZbIGCC5HK37C2Kr7+1RZK3tXNNV6HM03SCHJGGQvf+L0IGtAyscd8Ps1L+7meIB8ys1NPUKIi16H8wOSuITNxBW7CvfYMKTRbs/3tGqwKYs=
  - secure: uR3o4UXnMFpWco67TmNZLXZDAXopJNRd5TF3JkhM/hLnU96opRytsgvv9FNdshKHKBXvgIxLZzuFlGeNxT5UBnWJJkOE+PWlsJvZIyqYytR/8QpOzHjJ4U5XjLPJniKlTUxJkAEHjs4SNm6Q8UHC3fcgVMo6VNJ2lIYkvv8wIEcwOfH60k5sXTVpq4fQsBpJESNoF4apBestuK9k9DNfz2kmrmwGYq1iR/dzO5h55SJxHLd3ci1M/TiRgYctY8vzguJJy5pW+4beKv50uxfJXJeVt2ApgBvMybSFc6rO/8PXUYp0rVkiS69Wqq1VsUFhKx+Dec8DZwdDRR9LTjumHalUx5Vnwovv6rE9soxDqQ6VUShoQrFPv8DJRLKqnkax5QO+7NXD0dyG/zHXpdNRi4ZQmbPqekc+AWtB/J9Z5/XZJCk0XqVRN+8LwKBtlbhwBUxHcXsduyTgsEraFtG9vaSYM2ptTk5WwwL1+i4ZQVu6n3wc90/koVIS8q1fhHZ7Oe4L49rKPd3Zf1TuWVrpnRpBiTyrP/aJl4VVV/WWX1w6aahTESaDqg5Kff9w322DbaSQ5R2Yt1nJULiHiCbO/GkdZAcvad/zqzBdjHMYZa3w0MEilsaW6rGmXCoL5n1vajm0FiX5LOLXvAguvjMU2KLiAZKBTo9gk1nfLOG/+AA=
