service: why82-backend
custom:
  mysportsfeeds: ${file(.mysportsfeeds.yml)}
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - Fn::Join:
          - ':'
          - - arn
            - aws
            - s3
            - ''
            - ''
            - Ref: DataBucket
            - /*
  environment:
    MSF_USER: ${self:custom.mysportsfeeds.MSF_USER}
    MSF_PASS: ${self:custom.mysportsfeeds.MSF_PASS}
functions:
  save_stats:
    handler: handler.save_stats
    events:
    - http:
        path: hello
        method: GET
resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${opt:stage, self:provider.stage}
  Outputs:
    DataBucket:
      Description: 'The bucket where stats will be stored'
      Value:
        Ref: DataBucket
